apiVersion: v1
kind: Service
metadata:
  name: external-redis
spec:
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: external-redis
  labels:
    kubernetes.io/service-name: external-redis
    app: spring-web
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.18.64  # Your local computer IP
ports:
  - protocol: TCP
    port: 6379

