apiVersion: v1
kind: Pod
metadata:
    name: nginx
    namespace: spring-web
    labels:
        app: nginx
        type: frontend
spec:
    containers:
    - name: nginx
      image: nginx:latest
      ports:
      - containerPort: 80
      volumeMounts:
      - name: nginx-config
        mountPath: /etc/nginx/conf.d
        readOnly: true
      - name: nginx-static
        mountPath: /usr/share/nginx/html
        readOnly: true
      readinessProbe:
        httpGet:
          path: /healthz
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /healthz
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 20
    volumes:
    - name: nginx-config
      configMap:
        name: nginx-config
    - name: nginx-static
      configMap:
        name: nginx-static
