apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-web
  namespace: spring-web
  labels:
    app: spring-web
    type: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-web
      type: backend
  template:
    metadata:
      labels:
        app: spring-web
        type: backend
    spec:
      containers:
        - name: spring-web-app
          image: spring-web-app:latest
          imagePullPolicy: Never  # Use local image, don't pull from registry
          ports:
            - containerPort: 8080
          env:
            - name: spring.profiles.active
              value: "kubernetes"