spring.application.name=spring-web


spring.mongodb.host=localhost
spring.mongodb.port= 27017

spring.mongodb.database=pets

spring.threads.virtual.enabled=true

resilience4j.retry.instances.findPetByType.max-attempts=3
resilience4j.retry.instances.findPetByType.wait-duration=2s
resilience4j.retry.instances.findPetByType.enable-exponential-backoff=true
resilience4j.retry.instances.findPetByType.exponential-backoff-multiplier=2
resilience4j.retry.instances.findPetByType.retry-exceptions[0]=com.springweb.exception.PetNotFoundException


resilience4j.bulkhead.instances.findPetByType.max-concurrent-calls=1
resilience4j.bulkhead.instances.findPetByType.max-wait-duration=100ms


management.endpoints.web.exposure.include=health,metrics,beans,conditions,startup

spring.devtools.livereload.enabled=true
spring.devtools.restart.poll-interval=1s

# Enable Redis keyspace notifications for key expiry events
management.health.redis.enabled=true
spring.data.redis.host=localhost
spring.data.redis.port=6379
